/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedIndexRouteImport } from './routes/authed/index'
import { Route as SettingsAccountSettingsRouteImport } from './routes/settings/account-settings'
import { Route as AuthedTasksRouteImport } from './routes/authed/tasks'
import { Route as AuthedReportsRouteImport } from './routes/authed/reports'
import { Route as AuthedLeadsRouteImport } from './routes/authed/leads'
import { Route as AuthedDashboardRouteImport } from './routes/authed/dashboard'
import { Route as AuthedCommunicationRouteImport } from './routes/authed/communication'
import { Route as AuthedClientsRouteImport } from './routes/authed/clients'
import { Route as AuthedCampaignsRouteImport } from './routes/authed/campaigns'
import { Route as AuthedSettingsAccountSettingsRouteImport } from './routes/authed/settings/account-settings'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/authed',
  path: '/authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const SettingsAccountSettingsRoute = SettingsAccountSettingsRouteImport.update({
  id: '/settings/account-settings',
  path: '/settings/account-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTasksRoute = AuthedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeadsRoute = AuthedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCommunicationRoute = AuthedCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsRoute = AuthedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCampaignsRoute = AuthedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsAccountSettingsRoute =
  AuthedSettingsAccountSettingsRouteImport.update({
    id: '/settings/account-settings',
    path: '/settings/account-settings',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/authed/campaigns': typeof AuthedCampaignsRoute
  '/authed/clients': typeof AuthedClientsRoute
  '/authed/communication': typeof AuthedCommunicationRoute
  '/authed/dashboard': typeof AuthedDashboardRoute
  '/authed/leads': typeof AuthedLeadsRoute
  '/authed/reports': typeof AuthedReportsRoute
  '/authed/tasks': typeof AuthedTasksRoute
  '/settings/account-settings': typeof SettingsAccountSettingsRoute
  '/authed/': typeof AuthedIndexRoute
  '/authed/settings/account-settings': typeof AuthedSettingsAccountSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/authed/campaigns': typeof AuthedCampaignsRoute
  '/authed/clients': typeof AuthedClientsRoute
  '/authed/communication': typeof AuthedCommunicationRoute
  '/authed/dashboard': typeof AuthedDashboardRoute
  '/authed/leads': typeof AuthedLeadsRoute
  '/authed/reports': typeof AuthedReportsRoute
  '/authed/tasks': typeof AuthedTasksRoute
  '/settings/account-settings': typeof SettingsAccountSettingsRoute
  '/authed': typeof AuthedIndexRoute
  '/authed/settings/account-settings': typeof AuthedSettingsAccountSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/authed/campaigns': typeof AuthedCampaignsRoute
  '/authed/clients': typeof AuthedClientsRoute
  '/authed/communication': typeof AuthedCommunicationRoute
  '/authed/dashboard': typeof AuthedDashboardRoute
  '/authed/leads': typeof AuthedLeadsRoute
  '/authed/reports': typeof AuthedReportsRoute
  '/authed/tasks': typeof AuthedTasksRoute
  '/settings/account-settings': typeof SettingsAccountSettingsRoute
  '/authed/': typeof AuthedIndexRoute
  '/authed/settings/account-settings': typeof AuthedSettingsAccountSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authed'
    | '/login'
    | '/register'
    | '/authed/campaigns'
    | '/authed/clients'
    | '/authed/communication'
    | '/authed/dashboard'
    | '/authed/leads'
    | '/authed/reports'
    | '/authed/tasks'
    | '/settings/account-settings'
    | '/authed/'
    | '/authed/settings/account-settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/authed/campaigns'
    | '/authed/clients'
    | '/authed/communication'
    | '/authed/dashboard'
    | '/authed/leads'
    | '/authed/reports'
    | '/authed/tasks'
    | '/settings/account-settings'
    | '/authed'
    | '/authed/settings/account-settings'
  id:
    | '__root__'
    | '/'
    | '/authed'
    | '/login'
    | '/register'
    | '/authed/campaigns'
    | '/authed/clients'
    | '/authed/communication'
    | '/authed/dashboard'
    | '/authed/leads'
    | '/authed/reports'
    | '/authed/tasks'
    | '/settings/account-settings'
    | '/authed/'
    | '/authed/settings/account-settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsAccountSettingsRoute: typeof SettingsAccountSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authed': {
      id: '/authed'
      path: '/authed'
      fullPath: '/authed'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authed/campaigns': {
      id: '/authed/campaigns'
      path: '/campaigns'
      fullPath: '/authed/campaigns'
      preLoaderRoute: typeof AuthedCampaignsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/authed/clients': {
      id: '/authed/clients'
      path: '/clients'
      fullPath: '/authed/clients'
      preLoaderRoute: typeof AuthedClientsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/authed/communication': {
      id: '/authed/communication'
      path: '/communication'
      fullPath: '/authed/communication'
      preLoaderRoute: typeof AuthedCommunicationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/authed/dashboard': {
      id: '/authed/dashboard'
      path: '/dashboard'
      fullPath: '/authed/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/authed/leads': {
      id: '/authed/leads'
      path: '/leads'
      fullPath: '/authed/leads'
      preLoaderRoute: typeof AuthedLeadsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/authed/reports': {
      id: '/authed/reports'
      path: '/reports'
      fullPath: '/authed/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/authed/tasks': {
      id: '/authed/tasks'
      path: '/tasks'
      fullPath: '/authed/tasks'
      preLoaderRoute: typeof AuthedTasksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/settings/account-settings': {
      id: '/settings/account-settings'
      path: '/settings/account-settings'
      fullPath: '/settings/account-settings'
      preLoaderRoute: typeof SettingsAccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authed/': {
      id: '/authed/'
      path: '/'
      fullPath: '/authed/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/authed/settings/account-settings': {
      id: '/authed/settings/account-settings'
      path: '/settings/account-settings'
      fullPath: '/authed/settings/account-settings'
      preLoaderRoute: typeof AuthedSettingsAccountSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/authed' {
  const createFileRoute: CreateFileRoute<
    '/authed',
    FileRoutesByPath['/authed']['parentRoute'],
    FileRoutesByPath['/authed']['id'],
    FileRoutesByPath['/authed']['path'],
    FileRoutesByPath['/authed']['fullPath']
  >
}
declare module './routes/login' {
  const createFileRoute: CreateFileRoute<
    '/login',
    FileRoutesByPath['/login']['parentRoute'],
    FileRoutesByPath['/login']['id'],
    FileRoutesByPath['/login']['path'],
    FileRoutesByPath['/login']['fullPath']
  >
}
declare module './routes/register' {
  const createFileRoute: CreateFileRoute<
    '/register',
    FileRoutesByPath['/register']['parentRoute'],
    FileRoutesByPath['/register']['id'],
    FileRoutesByPath['/register']['path'],
    FileRoutesByPath['/register']['fullPath']
  >
}
declare module './routes/authed/campaigns' {
  const createFileRoute: CreateFileRoute<
    '/authed/campaigns',
    FileRoutesByPath['/authed/campaigns']['parentRoute'],
    FileRoutesByPath['/authed/campaigns']['id'],
    FileRoutesByPath['/authed/campaigns']['path'],
    FileRoutesByPath['/authed/campaigns']['fullPath']
  >
}
declare module './routes/authed/clients' {
  const createFileRoute: CreateFileRoute<
    '/authed/clients',
    FileRoutesByPath['/authed/clients']['parentRoute'],
    FileRoutesByPath['/authed/clients']['id'],
    FileRoutesByPath['/authed/clients']['path'],
    FileRoutesByPath['/authed/clients']['fullPath']
  >
}
declare module './routes/authed/communication' {
  const createFileRoute: CreateFileRoute<
    '/authed/communication',
    FileRoutesByPath['/authed/communication']['parentRoute'],
    FileRoutesByPath['/authed/communication']['id'],
    FileRoutesByPath['/authed/communication']['path'],
    FileRoutesByPath['/authed/communication']['fullPath']
  >
}
declare module './routes/authed/dashboard' {
  const createFileRoute: CreateFileRoute<
    '/authed/dashboard',
    FileRoutesByPath['/authed/dashboard']['parentRoute'],
    FileRoutesByPath['/authed/dashboard']['id'],
    FileRoutesByPath['/authed/dashboard']['path'],
    FileRoutesByPath['/authed/dashboard']['fullPath']
  >
}
declare module './routes/authed/leads' {
  const createFileRoute: CreateFileRoute<
    '/authed/leads',
    FileRoutesByPath['/authed/leads']['parentRoute'],
    FileRoutesByPath['/authed/leads']['id'],
    FileRoutesByPath['/authed/leads']['path'],
    FileRoutesByPath['/authed/leads']['fullPath']
  >
}
declare module './routes/authed/reports' {
  const createFileRoute: CreateFileRoute<
    '/authed/reports',
    FileRoutesByPath['/authed/reports']['parentRoute'],
    FileRoutesByPath['/authed/reports']['id'],
    FileRoutesByPath['/authed/reports']['path'],
    FileRoutesByPath['/authed/reports']['fullPath']
  >
}
declare module './routes/authed/tasks' {
  const createFileRoute: CreateFileRoute<
    '/authed/tasks',
    FileRoutesByPath['/authed/tasks']['parentRoute'],
    FileRoutesByPath['/authed/tasks']['id'],
    FileRoutesByPath['/authed/tasks']['path'],
    FileRoutesByPath['/authed/tasks']['fullPath']
  >
}
declare module './routes/settings/account-settings' {
  const createFileRoute: CreateFileRoute<
    '/settings/account-settings',
    FileRoutesByPath['/settings/account-settings']['parentRoute'],
    FileRoutesByPath['/settings/account-settings']['id'],
    FileRoutesByPath['/settings/account-settings']['path'],
    FileRoutesByPath['/settings/account-settings']['fullPath']
  >
}
declare module './routes/authed/index' {
  const createFileRoute: CreateFileRoute<
    '/authed/',
    FileRoutesByPath['/authed/']['parentRoute'],
    FileRoutesByPath['/authed/']['id'],
    FileRoutesByPath['/authed/']['path'],
    FileRoutesByPath['/authed/']['fullPath']
  >
}
declare module './routes/authed/settings/account-settings' {
  const createFileRoute: CreateFileRoute<
    '/authed/settings/account-settings',
    FileRoutesByPath['/authed/settings/account-settings']['parentRoute'],
    FileRoutesByPath['/authed/settings/account-settings']['id'],
    FileRoutesByPath['/authed/settings/account-settings']['path'],
    FileRoutesByPath['/authed/settings/account-settings']['fullPath']
  >
}

interface AuthedRouteChildren {
  AuthedCampaignsRoute: typeof AuthedCampaignsRoute
  AuthedClientsRoute: typeof AuthedClientsRoute
  AuthedCommunicationRoute: typeof AuthedCommunicationRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedLeadsRoute: typeof AuthedLeadsRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedTasksRoute: typeof AuthedTasksRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedSettingsAccountSettingsRoute: typeof AuthedSettingsAccountSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCampaignsRoute: AuthedCampaignsRoute,
  AuthedClientsRoute: AuthedClientsRoute,
  AuthedCommunicationRoute: AuthedCommunicationRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedLeadsRoute: AuthedLeadsRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedTasksRoute: AuthedTasksRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedSettingsAccountSettingsRoute: AuthedSettingsAccountSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsAccountSettingsRoute: SettingsAccountSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
