/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsAccountSettingsRouteImport } from './routes/settings/account-settings'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountSettingsRoute = SettingsAccountSettingsRouteImport.update({
  id: '/settings/account-settings',
  path: '/settings/account-settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/clients': typeof ClientsRoute
  '/communication': typeof CommunicationRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/settings/account-settings': typeof SettingsAccountSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/clients': typeof ClientsRoute
  '/communication': typeof CommunicationRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/settings/account-settings': typeof SettingsAccountSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/clients': typeof ClientsRoute
  '/communication': typeof CommunicationRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/reports': typeof ReportsRoute
  '/tasks': typeof TasksRoute
  '/settings/account-settings': typeof SettingsAccountSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/clients'
    | '/communication'
    | '/dashboard'
    | '/leads'
    | '/reports'
    | '/tasks'
    | '/settings/account-settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/clients'
    | '/communication'
    | '/dashboard'
    | '/leads'
    | '/reports'
    | '/tasks'
    | '/settings/account-settings'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/clients'
    | '/communication'
    | '/dashboard'
    | '/leads'
    | '/reports'
    | '/tasks'
    | '/settings/account-settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRoute
  ClientsRoute: typeof ClientsRoute
  CommunicationRoute: typeof CommunicationRoute
  DashboardRoute: typeof DashboardRoute
  LeadsRoute: typeof LeadsRoute
  ReportsRoute: typeof ReportsRoute
  TasksRoute: typeof TasksRoute
  SettingsAccountSettingsRoute: typeof SettingsAccountSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account-settings': {
      id: '/settings/account-settings'
      path: '/settings/account-settings'
      fullPath: '/settings/account-settings'
      preLoaderRoute: typeof SettingsAccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/campaigns' {
  const createFileRoute: CreateFileRoute<
    '/campaigns',
    FileRoutesByPath['/campaigns']['parentRoute'],
    FileRoutesByPath['/campaigns']['id'],
    FileRoutesByPath['/campaigns']['path'],
    FileRoutesByPath['/campaigns']['fullPath']
  >
}
declare module './routes/clients' {
  const createFileRoute: CreateFileRoute<
    '/clients',
    FileRoutesByPath['/clients']['parentRoute'],
    FileRoutesByPath['/clients']['id'],
    FileRoutesByPath['/clients']['path'],
    FileRoutesByPath['/clients']['fullPath']
  >
}
declare module './routes/communication' {
  const createFileRoute: CreateFileRoute<
    '/communication',
    FileRoutesByPath['/communication']['parentRoute'],
    FileRoutesByPath['/communication']['id'],
    FileRoutesByPath['/communication']['path'],
    FileRoutesByPath['/communication']['fullPath']
  >
}
declare module './routes/dashboard' {
  const createFileRoute: CreateFileRoute<
    '/dashboard',
    FileRoutesByPath['/dashboard']['parentRoute'],
    FileRoutesByPath['/dashboard']['id'],
    FileRoutesByPath['/dashboard']['path'],
    FileRoutesByPath['/dashboard']['fullPath']
  >
}
declare module './routes/leads' {
  const createFileRoute: CreateFileRoute<
    '/leads',
    FileRoutesByPath['/leads']['parentRoute'],
    FileRoutesByPath['/leads']['id'],
    FileRoutesByPath['/leads']['path'],
    FileRoutesByPath['/leads']['fullPath']
  >
}
declare module './routes/reports' {
  const createFileRoute: CreateFileRoute<
    '/reports',
    FileRoutesByPath['/reports']['parentRoute'],
    FileRoutesByPath['/reports']['id'],
    FileRoutesByPath['/reports']['path'],
    FileRoutesByPath['/reports']['fullPath']
  >
}
declare module './routes/tasks' {
  const createFileRoute: CreateFileRoute<
    '/tasks',
    FileRoutesByPath['/tasks']['parentRoute'],
    FileRoutesByPath['/tasks']['id'],
    FileRoutesByPath['/tasks']['path'],
    FileRoutesByPath['/tasks']['fullPath']
  >
}
declare module './routes/settings/account-settings' {
  const createFileRoute: CreateFileRoute<
    '/settings/account-settings',
    FileRoutesByPath['/settings/account-settings']['parentRoute'],
    FileRoutesByPath['/settings/account-settings']['id'],
    FileRoutesByPath['/settings/account-settings']['path'],
    FileRoutesByPath['/settings/account-settings']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRoute,
  ClientsRoute: ClientsRoute,
  CommunicationRoute: CommunicationRoute,
  DashboardRoute: DashboardRoute,
  LeadsRoute: LeadsRoute,
  ReportsRoute: ReportsRoute,
  TasksRoute: TasksRoute,
  SettingsAccountSettingsRoute: SettingsAccountSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
